import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { RequestCookie } from "next/dist/compiled/@edge-runtime/cookies";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hassy Team™",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get("theme")?.value;
  console.log(theme)

  return (
    <html lang="en">
      <body className={outfit.className + " " + theme}>
        {children}
      </body>
    </html>
  );
}
